
CREATE TABLE IF NOT EXISTS eg_employee_data(
empCode VARCHAR(255)  PRIMARY KEY,
empCity VARCHAR(255) ,
empDepartment VARCHAR(255) ,
empDesignation VARCHAR(255) ,
empDistrict VARCHAR(255) ,
empDob VARCHAR(255) ,
empEmail VARCHAR(255) ,
empEmptype VARCHAR(50) ,
empFname VARCHAR(255) ,
empGender VARCHAR(50) ,
empJoining VARCHAR(255) ,
empLname VARCHAR(255) ,
empMname VARCHAR(255) ,
empMob VARCHAR(255) ,
empPlaceofpost VARCHAR(255) ,
empPostal BIGINT ,
empRetirement VARCHAR(200) ,
empStreet1 VARCHAR(255) ,
empStreet2 VARCHAR(255) ,
status VARCHAR(200) ,
createdAt BIGINT NOT NULL,
updatedAt BIGINT,
createdBy VARCHAR(50) NOT NULL ,
updatedBy VARCHAR(50));