-- Create table if not EXISTS eg_employee_data
CREATE TABLE eg_employee_data(
empCode SERIAL PRIMARY KEY,
empCity 	VARCHAR(255) NOT NULL,
empDepartment VARCHAR(255) NOT NULL,
empDesignation VARCHAR(255) NOT NULL,
empDistrict VARCHAR(255) NOT NULL,
empDob BIGINT NOT NULL,
empEmail VARCHAR(255) NOT NULL,
empEmptype VARCHAR(50) NOT NULL,
empFname VARCHAR(255) NOT NULL,
empGender VARCHAR(50) NOT NULL,
empJoining BIGINT NOT NULL,
empLname VARCHAR(255) NOT NULL,
empMname VARCHAR(255) NOT NULL,
empMob VARCHAR(255) NOT NULL,
empPlaceofpost VARCHAR(255) NOT NULL,
empPostal BIGINT NOT NULL,
empRetirement BIGINT NOT NULL,
empStreet1 VARCHAR(255) NOT NULL,
empStreet2 VARCHAR(255) NOT NULL,
status VARCHAR(200) NOT NULL,
createdAt BIGINT NOT NULL,
updatedAt BIGINT,
createdBy VARCHAR(50) NOT NULL,
updatedBy VARCHAR(50));